"""Generate ``firmware/arm_esp32/src/config_generated.h`` from ArmSettings.

Single source of truth for hardware tunables: this script reads the same
:class:`armdroid.config.schema.ArmSettings` that the host loads at runtime
and emits a C++ header consumed by the ESP32 firmware build.

Run as a PlatformIO pre-build step (see
``firmware/arm_esp32/platformio.ini``) or manually:

.. code-block:: bash

    python scripts/gen_firmware_config.py
    python scripts/gen_firmware_config.py --config config/tower_of_hanoi.yaml
    python scripts/gen_firmware_config.py --check    # CI drift gate
    python scripts/gen_firmware_config.py --secrets-file .secrets/wifi.env

The ``--check`` mode exits non-zero if the on-disk header differs from the
freshly computed one, so CI can block merges that change YAML without
regenerating the header.

The ``--secrets-file`` flag accepts a dotenv-style file with WiFi credentials
and HMAC key.  When absent, WiFi and BLE are compiled out.  The secrets file
is **never** committed — it lives in ``.secrets/`` which is gitignored.
See ``.secrets/wifi.env.example`` for the expected key names.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "firmware" / "arm_esp32" / "src" / "config_generated.h"

# Make ``armdroid`` importable when running from a checkout without an
# editable install. PlatformIO pre-build steps invoke this script from
# a fresh subprocess that does not inherit any virtualenv.
_SRC = REPO_ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from armdroid.config.schema import ArmSettings, load_settings  # noqa: E402

# ---------------------------------------------------------------------------
# Secrets file parsing
# ---------------------------------------------------------------------------


class _Secrets(NamedTuple):
    wifi_ssid: str
    wifi_password: str
    hmac_key_hex: str
    tcp_port: int
    wifi_enabled: bool
    hmac_enabled: bool


_SECRETS_DISABLED: _Secrets = _Secrets(
    wifi_ssid="",
    wifi_password="",
    hmac_key_hex="",
    tcp_port=3001,
    wifi_enabled=False,
    hmac_enabled=False,
)


def _load_secrets(path: Path) -> _Secrets:
    """Parse a dotenv-style file and return a :class:`_Secrets` tuple.

    Lines starting with ``#`` are comments.  Keys are stripped of surrounding
    quotes on the value side.  Missing keys default to empty strings.

    Raises:
        SystemExit: If the file contains a malformed HMAC key.
    """
    raw: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        raw[key.strip()] = val.strip().strip('"').strip("'")

    ssid = raw.get("ARMDROID_WIFI_SSID", "")
    password = raw.get("ARMDROID_WIFI_PASS", "")
    hmac_key = raw.get("ARMDROID_HMAC_KEY", "")
    try:
        tcp_port = int(raw.get("ARMDROID_TCP_PORT", "3001"))
    except ValueError:
        sys.stderr.write("[gen_firmware_config] ARMDROID_TCP_PORT must be an integer\n")
        sys.exit(1)
    # The generated header emits the port into a uint16_t, so validate
    # the range before we silently truncate / wrap. <=0 is nonsensical
    # for a TCP listen port.
    if not 1 <= tcp_port <= 65535:
        sys.stderr.write("[gen_firmware_config] ARMDROID_TCP_PORT must be between 1 and 65535\n")
        sys.exit(1)

    if hmac_key:
        # Validate: must be valid hex and at least 32 hex chars (16 bytes)
        if not re.fullmatch(r"[0-9a-fA-F]+", hmac_key):
            sys.stderr.write("[gen_firmware_config] ARMDROID_HMAC_KEY is not valid hex\n")
            sys.exit(1)
        if len(hmac_key) < 32:
            sys.stderr.write(
                "[gen_firmware_config] ARMDROID_HMAC_KEY must be at least 32 hex chars (16 bytes)\n"
            )
            sys.exit(1)

    wifi_enabled = bool(ssid)
    hmac_enabled = bool(hmac_key)
    return _Secrets(
        wifi_ssid=ssid,
        wifi_password=password,
        hmac_key_hex=hmac_key.lower(),
        tcp_port=tcp_port,
        wifi_enabled=wifi_enabled,
        hmac_enabled=hmac_enabled,
    )


# Header banner reused for both write and --check modes.
_BANNER = (
    "// AUTO-GENERATED by scripts/gen_firmware_config.py\n"
    "// DO NOT EDIT this file by hand. Regenerate with:\n"
    "//\n"
    "//     python scripts/gen_firmware_config.py [--config FILE]...\n"
    "//\n"
    "// Source of truth: armdroid.config.schema.ArmSettings.\n"
    "// CI runs `--check` to catch drift between this header and the YAML.\n"
)


def _c_str(s: str) -> str:
    """Escape a Python string for embedding in a C string literal.

    Handles backslash and double-quote (the obvious cases) plus
    newline / carriage-return / tab so a SSID or password containing
    those characters does not break the generated C++ header. Any other
    non-printable control character would still produce broken output;
    those are extremely rare in WiFi credentials and the firmware will
    fail to compile rather than silently mis-parse.
    """
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def _format_float_array(values: list[float], suffix: str = "f") -> str:
    """Format a list of floats as a C++ array initializer body."""
    return ", ".join(f"{v:.6f}{suffix}" for v in values)


def _format_int_array(values: list[int]) -> str:
    """Format a list of ints as a C++ array initializer body."""
    return ", ".join(str(v) for v in values)


def render_header(cfg: ArmSettings, secrets: _Secrets | None = None) -> str:
    """Render the full C++ header for the given ArmSettings.

    Args:
        cfg: Validated armdroid settings root.
        secrets: Optional secrets (WiFi SSID/password, HMAC key, TCP port).
            When ``None``, WiFi and BLE transports are compiled out.

    Returns:
        Complete ``config_generated.h`` content as a string.
    """
    if secrets is None:
        secrets = _SECRETS_DISABLED
    arm = cfg.arm
    interp_period_ms = max(1, round(1000.0 / arm.firmware.interpolator_hz))
    heartbeat_period_ms = max(1, round(1000.0 / arm.transport.heartbeat_hz))
    watchdog_timeout_ms = max(1, round(arm.firmware.watchdog_timeout_s * 1000.0))

    pins = _format_int_array([s.pwm_pin for s in arm.servos])
    pulse_min = _format_int_array([s.pulse_min_us for s in arm.servos])
    pulse_max = _format_int_array([s.pulse_max_us for s in arm.servos])
    joint_min = _format_float_array([lim.min_rad for lim in arm.joint_limits])
    joint_max = _format_float_array([lim.max_rad for lim in arm.joint_limits])

    fw_version = arm.firmware.firmware_version.replace('"', '\\"')
    wifi_enabled_str = "true" if secrets.wifi_enabled else "false"
    hmac_enabled_str = "true" if secrets.hmac_enabled else "false"
    return (
        f"{_BANNER}\n"
        "#pragma once\n"
        "\n"
        "// Arduino.h is only available in the embedded toolchain, not in the\n"
        "// native test environment.  Guard it so `pio test -e native` works.\n"
        "#ifndef UNIT_TEST\n"
        "#include <Arduino.h>\n"
        "#else\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "#endif  // UNIT_TEST\n"
        "\n"
        "namespace armdroid::firmware::config {\n"
        "\n"
        "// Joint count. Must match host ArmDriverProtocol joint vector length.\n"
        f"constexpr size_t kNumJoints = {arm.dof};\n"
        "\n"
        "// Servo PWM pins on the ESP32 (one per joint).\n"
        f"constexpr uint8_t kServoPins[kNumJoints] = {{ {pins} }};\n"
        "\n"
        "// Joint limits.\n"
        "//   Rotational joints: radians.\n"
        "//   Gripper (last joint, when gripper_type != 'none'): normalised [0, 1].\n"
        "// Defence-in-depth: the host enforces these too; firmware limits are the floor.\n"
        f"constexpr float kJointMin[kNumJoints] = {{ {joint_min} }};\n"
        f"constexpr float kJointMax[kNumJoints] = {{ {joint_max} }};\n"
        "\n"
        "// Servo pulse-width calibration (microseconds at the joint's mechanical limits).\n"
        f"constexpr int kPulseMinUs[kNumJoints] = {{ {pulse_min} }};\n"
        f"constexpr int kPulseMaxUs[kNumJoints] = {{ {pulse_max} }};\n"
        "\n"
        "// Loop cadence — derived from host-side Hz settings.\n"
        f"constexpr uint32_t kInterpolatorPeriodMs = {interp_period_ms};\n"
        f"constexpr uint32_t kHeartbeatPeriodMs = {heartbeat_period_ms};\n"
        f"constexpr uint32_t kWatchdogTimeoutMs = {watchdog_timeout_ms};\n"
        "\n"
        "// Wire framing — must match ArmTransportConfig on the host.\n"
        f"constexpr size_t kMaxLineBytes = {arm.transport.max_line_bytes};\n"
        "constexpr size_t kJsonDocCapacity = 1024;\n"
        f"constexpr uint32_t kSerialBaud = {arm.transport.serial_baud};\n"
        "\n"
        "// Firmware version — emitted in the boot evt frame.\n"
        f'constexpr const char* kFirmwareVersion = "{fw_version}";\n'
        "\n"
        "// WiFi / TCP transport.\n"
        f"constexpr bool kWiFiEnabled = {wifi_enabled_str};\n"
        f'constexpr const char* kWiFiSSID = "{_c_str(secrets.wifi_ssid)}";\n'
        f'constexpr const char* kWiFiPassword = "{_c_str(secrets.wifi_password)}";\n'
        f"constexpr uint16_t kTcpPort = {secrets.tcp_port};\n"
        "\n"
        "// HMAC-SHA256 authentication.\n"
        f"constexpr bool kHmacEnabled = {hmac_enabled_str};\n"
        f'constexpr const char* kHmacKeyHex = "{secrets.hmac_key_hex}";\n'
        "\n"
        "}  // namespace armdroid::firmware::config\n"
    )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments.

    Args:
        argv: Optional argv override (for tests).

    Returns:
        Parsed argparse Namespace.
    """
    parser = argparse.ArgumentParser(
        prog="gen_firmware_config",
        description=(
            "Generate firmware/arm_esp32/src/config_generated.h from ArmSettings. "
            "Source of truth: armdroid.config.schema.ArmSettings."
        ),
    )
    parser.add_argument(
        "--config",
        type=Path,
        action="append",
        default=[],
        help=(
            "YAML config overlay file. Repeat to layer multiple overlays "
            "(merged in order on top of the built-in defaults)."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Header path to write. Default: {DEFAULT_OUTPUT}",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Do not write. Exit 0 if the on-disk header matches the computed "
            "one; exit 1 if it differs (or is missing). Used by CI to catch "
            "host/firmware drift."
        ),
    )
    parser.add_argument(
        "--secrets-file",
        type=Path,
        default=None,
        metavar="PATH",
        help=(
            "Dotenv-style file with WiFi / HMAC secrets "
            "(ARMDROID_WIFI_SSID, ARMDROID_WIFI_PASS, ARMDROID_HMAC_KEY, "
            "ARMDROID_TCP_PORT). "
            "When absent, WiFi and BLE are compiled out. "
            "This file is gitignored and must never be committed. "
            "See .secrets/wifi.env.example."
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Entry point. Returns process exit code."""
    args = parse_args(argv)
    cfg = load_settings(*args.config)

    secrets: _Secrets | None = None
    if args.secrets_file is not None:
        secrets_path: Path = args.secrets_file
        if not secrets_path.exists():
            sys.stderr.write(f"[gen_firmware_config] secrets file not found: {secrets_path}\n")
            return 1
        secrets = _load_secrets(secrets_path)

    rendered = render_header(cfg, secrets=secrets)

    output_path: Path = args.output
    # Security guard: the default ``DEFAULT_OUTPUT`` path is tracked in
    # git (codegen-check validates the committed header stays in sync
    # with ArmSettings). Writing a secrets-bearing header to that path
    # is one ``git add`` away from leaking WiFi credentials and the
    # HMAC key. Refuse the write and require an explicit ``--output``
    # so the operator has to think about where the secrets-bearing
    # header lands. Local-only paths can be added to .gitignore (see
    # the ``firmware/arm_esp32/src/`` block).
    secrets_present = secrets is not None and (secrets.wifi_enabled or secrets.hmac_enabled)
    if secrets_present and not args.check and output_path == DEFAULT_OUTPUT:
        sys.stderr.write(
            "[gen_firmware_config] refusing to write secrets-bearing header to "
            f"{output_path} — that file is tracked in git. Re-run with "
            "--output <path> pointing at a gitignored location "
            "(e.g. firmware/arm_esp32/src/config_generated_with_secrets.h).\n"
        )
        return 1
    if args.check:
        if not output_path.exists():
            sys.stderr.write(
                f"[gen_firmware_config] {output_path} does not exist — run "
                "without --check to generate it.\n"
            )
            return 1
        existing = output_path.read_text(encoding="utf-8")
        if existing != rendered:
            sys.stderr.write(
                f"[gen_firmware_config] {output_path} is stale relative to "
                "ArmSettings. Re-run scripts/gen_firmware_config.py.\n"
            )
            return 1
        sys.stdout.write(f"[gen_firmware_config] {output_path} is up to date.\n")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == rendered:
        sys.stdout.write(f"[gen_firmware_config] {output_path} unchanged.\n")
        return 0
    output_path.write_text(rendered, encoding="utf-8")
    sys.stdout.write(f"[gen_firmware_config] wrote {output_path}\n")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
