"""Generate ``firmware/arm_esp32/src/config_generated.h`` from ArmSettings.

Single source of truth for hardware tunables: this script reads the same
:class:`armdroid.config.schema.ArmSettings` that the host loads at runtime
and emits a C++ header consumed by the ESP32 firmware build.

Run as a PlatformIO pre-build step (see
``firmware/arm_esp32/platformio.ini``) or manually:

.. code-block:: bash

    python scripts/gen_firmware_config.py
    python scripts/gen_firmware_config.py --config config/tower_of_hanoi.yaml
    python scripts/gen_firmware_config.py --check    # CI drift gate

The ``--check`` mode exits non-zero if the on-disk header differs from the
freshly computed one, so CI can block merges that change YAML without
regenerating the header.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "firmware" / "arm_esp32" / "src" / "config_generated.h"

# Make ``armdroid`` importable when running from a checkout without an
# editable install. PlatformIO pre-build steps invoke this script from
# a fresh subprocess that does not inherit any virtualenv.
_SRC = REPO_ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from armdroid.config.schema import ArmSettings, load_settings  # noqa: E402

# Header banner reused for both write and --check modes.
_BANNER = (
    "// AUTO-GENERATED by scripts/gen_firmware_config.py\n"
    "// DO NOT EDIT this file by hand. Regenerate with:\n"
    "//\n"
    "//     python scripts/gen_firmware_config.py [--config FILE]...\n"
    "//\n"
    "// Source of truth: armdroid.config.schema.ArmSettings.\n"
    "// CI runs `--check` to catch drift between this header and the YAML.\n"
)


def _format_float_array(values: list[float], suffix: str = "f") -> str:
    """Format a list of floats as a C++ array initializer body."""
    return ", ".join(f"{v:.6f}{suffix}" for v in values)


def _format_int_array(values: list[int]) -> str:
    """Format a list of ints as a C++ array initializer body."""
    return ", ".join(str(v) for v in values)


def render_header(cfg: ArmSettings) -> str:
    """Render the full C++ header for the given ArmSettings.

    Args:
        cfg: Validated armdroid settings root.

    Returns:
        Complete ``config_generated.h`` content as a string.
    """
    arm = cfg.arm
    interp_period_ms = max(1, round(1000.0 / arm.firmware.interpolator_hz))
    heartbeat_period_ms = max(1, round(1000.0 / arm.transport.heartbeat_hz))
    watchdog_timeout_ms = max(1, round(arm.firmware.watchdog_timeout_s * 1000.0))

    pins = _format_int_array([s.pwm_pin for s in arm.servos])
    pulse_min = _format_int_array([s.pulse_min_us for s in arm.servos])
    pulse_max = _format_int_array([s.pulse_max_us for s in arm.servos])
    joint_min = _format_float_array([lim.min_rad for lim in arm.joint_limits])
    joint_max = _format_float_array([lim.max_rad for lim in arm.joint_limits])

    fw_version = arm.firmware.firmware_version.replace('"', '\\"')

    return (
        f"{_BANNER}\n"
        "#pragma once\n"
        "\n"
        "#include <Arduino.h>\n"
        "\n"
        "namespace armdroid::firmware::config {\n"
        "\n"
        "// Joint count. Must match host ArmDriverProtocol joint vector length.\n"
        f"constexpr size_t kNumJoints = {arm.dof};\n"
        "\n"
        "// Servo PWM pins on the ESP32 (one per joint).\n"
        f"constexpr uint8_t kServoPins[kNumJoints] = {{ {pins} }};\n"
        "\n"
        "// Joint limits.\n"
        "//   Rotational joints: radians.\n"
        "//   Gripper (last joint, when gripper_type != 'none'): normalised [0, 1].\n"
        "// Defence-in-depth: the host enforces these too; firmware limits are the floor.\n"
        f"constexpr float kJointMin[kNumJoints] = {{ {joint_min} }};\n"
        f"constexpr float kJointMax[kNumJoints] = {{ {joint_max} }};\n"
        "\n"
        "// Servo pulse-width calibration (microseconds at the joint's mechanical limits).\n"
        f"constexpr int kPulseMinUs[kNumJoints] = {{ {pulse_min} }};\n"
        f"constexpr int kPulseMaxUs[kNumJoints] = {{ {pulse_max} }};\n"
        "\n"
        "// Loop cadence — derived from host-side Hz settings.\n"
        f"constexpr uint32_t kInterpolatorPeriodMs = {interp_period_ms};\n"
        f"constexpr uint32_t kHeartbeatPeriodMs = {heartbeat_period_ms};\n"
        f"constexpr uint32_t kWatchdogTimeoutMs = {watchdog_timeout_ms};\n"
        "\n"
        "// Wire framing — must match ArmTransportConfig on the host.\n"
        f"constexpr size_t kMaxLineBytes = {arm.transport.max_line_bytes};\n"
        "constexpr size_t kJsonDocCapacity = 1024;\n"
        f"constexpr uint32_t kSerialBaud = {arm.transport.serial_baud};\n"
        "\n"
        "// Firmware version — emitted in the boot evt frame.\n"
        f'constexpr const char* kFirmwareVersion = "{fw_version}";\n'
        "\n"
        "}  // namespace armdroid::firmware::config\n"
    )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments.

    Args:
        argv: Optional argv override (for tests).

    Returns:
        Parsed argparse Namespace.
    """
    parser = argparse.ArgumentParser(
        prog="gen_firmware_config",
        description=(
            "Generate firmware/arm_esp32/src/config_generated.h from ArmSettings. "
            "Source of truth: armdroid.config.schema.ArmSettings."
        ),
    )
    parser.add_argument(
        "--config",
        type=Path,
        action="append",
        default=[],
        help=(
            "YAML config overlay file. Repeat to layer multiple overlays "
            "(merged in order on top of the built-in defaults)."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Header path to write. Default: {DEFAULT_OUTPUT}",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Do not write. Exit 0 if the on-disk header matches the computed "
            "one; exit 1 if it differs (or is missing). Used by CI to catch "
            "host/firmware drift."
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Entry point. Returns process exit code."""
    args = parse_args(argv)
    cfg = load_settings(*args.config)
    rendered = render_header(cfg)

    output_path: Path = args.output
    if args.check:
        if not output_path.exists():
            sys.stderr.write(
                f"[gen_firmware_config] {output_path} does not exist — run "
                "without --check to generate it.\n"
            )
            return 1
        existing = output_path.read_text(encoding="utf-8")
        if existing != rendered:
            sys.stderr.write(
                f"[gen_firmware_config] {output_path} is stale relative to "
                "ArmSettings. Re-run scripts/gen_firmware_config.py.\n"
            )
            return 1
        sys.stdout.write(f"[gen_firmware_config] {output_path} is up to date.\n")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == rendered:
        sys.stdout.write(f"[gen_firmware_config] {output_path} unchanged.\n")
        return 0
    output_path.write_text(rendered, encoding="utf-8")
    sys.stdout.write(f"[gen_firmware_config] wrote {output_path}\n")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
