// AUTO-GENERATED by scripts/gen_firmware_config.py
// DO NOT EDIT this file by hand. Regenerate with:
//
//     python scripts/gen_firmware_config.py [--config FILE]...
//
// Source of truth: armdroid.config.schema.ArmSettings.
// CI runs `--check` to catch drift between this header and the YAML.

#pragma once

#include <Arduino.h>

namespace armdroid::firmware::config {

// Joint count. Must match host ArmDriverProtocol joint vector length.
constexpr size_t kNumJoints = 6;

// Servo PWM pins on the ESP32 (one per joint).
constexpr uint8_t kServoPins[kNumJoints] = { 13, 14, 27, 26, 25, 33 };

// Joint limits.
//   Rotational joints: radians.
//   Gripper (last joint, when gripper_type != 'none'): normalised [0, 1].
// Defence-in-depth: the host enforces these too; firmware limits are the floor.
constexpr float kJointMin[kNumJoints] = { -1.570800f, -0.500000f, -1.570800f, -1.570800f, -1.570800f, -1.570800f };
constexpr float kJointMax[kNumJoints] = { 1.570800f, 1.570800f, 1.570800f, 1.570800f, 1.570800f, 1.570800f };

// Servo pulse-width calibration (microseconds at the joint's mechanical limits).
constexpr int kPulseMinUs[kNumJoints] = { 500, 500, 500, 500, 500, 500 };
constexpr int kPulseMaxUs[kNumJoints] = { 2500, 2500, 2500, 2500, 2500, 2500 };

// Loop cadence — derived from host-side Hz settings.
constexpr uint32_t kInterpolatorPeriodMs = 20;
constexpr uint32_t kHeartbeatPeriodMs = 100;
constexpr uint32_t kWatchdogTimeoutMs = 2000;

// Wire framing — must match ArmTransportConfig on the host.
constexpr size_t kMaxLineBytes = 512;
constexpr size_t kJsonDocCapacity = 1024;
constexpr uint32_t kSerialBaud = 115200;

// Firmware version — emitted in the boot evt frame.
constexpr const char* kFirmwareVersion = "arm-esp32-1.0.0";

}  // namespace armdroid::firmware::config
